apiVersion: release-notes/v2
kind: feature
area: policy and telemetry
issue:
  - 23580
releaseNotes:
- |
  **Added** Envoy [ext authz and gRPC access log API support](https://github.com/istio/istio/wiki/Enabling-Envoy-Authorization-Service-and-gRPC-Access-Log-Service-With-Mixer) in Mixer,
  which makes Mixer based configuration and out of process adapter still work after upgrading to future version of Istio. 
