apiVersion: v1
kind: Namespace
metadata:
  name: config-update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ servicerouteSAName }}
  namespace: config-update
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ podName }}
  namespace: config-update
spec:
  containers:
  - image: amd64/ubuntu:focal
    name: tctl-container
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - |
      apt update && apt install curl -y
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      PROVIDER={{ provider }}
      if [[ ${PROVIDER} == "aws" ]]; then
        IP=$(kubectl get svc envoy -n tsb -o "jsonpath={.status.loadBalancer.ingress[0].hostname}")
      else
        IP=$(kubectl get svc envoy -n tsb -o "jsonpath={.status.loadBalancer.ingress[0].ip}")
      fi
      echo "IP = $IP"
      mkdir -p ~/.tctl/bin
      curl -Lo ~/.tctl/bin/tctl https://binaries.dl.tetrate.io/public/raw/versions/linux-amd64-1.2.0/tctl
      chmod +x ~/.tctl/bin/tctl
      export PATH=$PATH:~/.tctl/bin
      tctl config clusters set demo --bridge-address $IP:8443
      tctl config users set admin --username admin --password "{{ password }}"
      tctl config profiles set demo --username admin --cluster demo
      tctl config profiles set-current demo
      tctl login --org {{ orgName }} --password "{{ password }}" --username admin --tenant {{ tenant }}

      cat >version1.yaml<<EOF
      apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        annotations:
          tsb.tetrate.io/tenant: {{ tenant }}
          tsb.tetrate.io/organization: {{ orgName }}
          tsb.tetrate.io/trafficGroup: {{ trafficGroupName }}
          tsb.tetrate.io/workspace: {{ workspaceName }}
        name: {{ serviceRouteName }}
        namespace: {{ ns }}
      spec:
        gateways:
        - mesh
        hosts:
        - {{ hostFQDN }}
        http:
        - route:
          - destination:
              host: {{ hostFQDN }}
              subset: v1
            weight: 50
          - destination:
              host: {{ hostFQDN }}
              subset: v2
            weight: 20
          - destination:
              host: {{ hostFQDN }}
              subset: v3
            weight: 30
      EOF
        
      cat >version2.yaml<<EOF
      apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        annotations:
          tsb.tetrate.io/tenant: {{ tenant }}
          tsb.tetrate.io/organization: {{ orgName }}
          tsb.tetrate.io/trafficGroup: {{ trafficGroupName }}
          tsb.tetrate.io/workspace: {{ workspaceName }}
        name: {{ serviceRouteName }}
        namespace: {{ ns }}
      spec:
        gateways:
        - mesh
        hosts:
        - {{ hostFQDN }}
        http:
        - route:
          - destination:
              host: {{ hostFQDN }}
              subset: v1
            weight: 60
          - destination:
              host: {{ hostFQDN }}
              subset: v2
            weight: 30
          - destination:
              host: {{ hostFQDN }}
              subset: v3
            weight: 10
      EOF
      while :; do
        echo "Applying version 1"
        tctl apply -f version1.yaml
        sleep 100
        echo "Applying version 2"
        tctl apply -f version2.yaml
        sleep 100
      done
  serviceAccount: {{ servicerouteSAName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tsb
  name: {{ servicerouteSAName }}-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ servicerouteSAName }}-binding
  namespace: tsb
subjects:
- kind: ServiceAccount
  name: {{ servicerouteSAName }}
  namespace: config-update
roleRef:
  kind: Role
  name: {{ servicerouteSAName }}-reader
  apiGroup: ""
