apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    tsb.tetrate.io/gatewayGroup: {{ gatewayGroupName }}
    tsb.tetrate.io/tenant: {{ tenantName }}
    tsb.tetrate.io/organization: {{ orgName }}
    tsb.tetrate.io/workspace: {{ workspaceName }}
  name: {{ virtualserviceName }}
  namespace: {{ (namespaces and namespaces['product']) or namespace }}
spec:
  exportTo:
  - .
  gateways:
  - {{ (namespaces and namespaces['product']) or namespace }}/{{ gatewayName }}
  hosts:
  - {{ hostname }}
  http:
  - name: http
    route:
    - destination:
        host: {{ destinationFQDN }}
      weight: 100
