// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

// Generate with protoc --go_out=plugins=grpc:. echo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{2}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ForwardEchoRequest struct {
	Count         int32     `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Qps           int32     `protobuf:"varint,2,opt,name=qps,proto3" json:"qps,omitempty"`
	TimeoutMicros int64     `protobuf:"varint,3,opt,name=timeout_micros,json=timeoutMicros,proto3" json:"timeout_micros,omitempty"`
	Url           string    `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*Header `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	Message       string    `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// If true, requests will be sent using h2c prior knowledge
	Http2 bool `protobuf:"varint,7,opt,name=http2,proto3" json:"http2,omitempty"`
	// If non-empty, make the request with the corresponding cert and key.
	Cert string `protobuf:"bytes,10,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  string `protobuf:"bytes,11,opt,name=key,proto3" json:"key,omitempty"`
	// List of ALPNs to present. If not set, this will be automatically be set based on the protocol
	Alpn *Alpn `protobuf:"bytes,13,opt,name=alpn,proto3" json:"alpn,omitempty"`
	// Server name (SNI) to present in TLS connections. If not set, Host will be used for http requests.
	ServerName           string   `protobuf:"bytes,20,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardEchoRequest) Reset()         { *m = ForwardEchoRequest{} }
func (m *ForwardEchoRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardEchoRequest) ProtoMessage()    {}
func (*ForwardEchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{3}
}

func (m *ForwardEchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardEchoRequest.Unmarshal(m, b)
}
func (m *ForwardEchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardEchoRequest.Marshal(b, m, deterministic)
}
func (m *ForwardEchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardEchoRequest.Merge(m, src)
}
func (m *ForwardEchoRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardEchoRequest.Size(m)
}
func (m *ForwardEchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardEchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardEchoRequest proto.InternalMessageInfo

func (m *ForwardEchoRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ForwardEchoRequest) GetQps() int32 {
	if m != nil {
		return m.Qps
	}
	return 0
}

func (m *ForwardEchoRequest) GetTimeoutMicros() int64 {
	if m != nil {
		return m.TimeoutMicros
	}
	return 0
}

func (m *ForwardEchoRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ForwardEchoRequest) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ForwardEchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ForwardEchoRequest) GetHttp2() bool {
	if m != nil {
		return m.Http2
	}
	return false
}

func (m *ForwardEchoRequest) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *ForwardEchoRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ForwardEchoRequest) GetAlpn() *Alpn {
	if m != nil {
		return m.Alpn
	}
	return nil
}

func (m *ForwardEchoRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type Alpn struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alpn) Reset()         { *m = Alpn{} }
func (m *Alpn) String() string { return proto.CompactTextString(m) }
func (*Alpn) ProtoMessage()    {}
func (*Alpn) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{4}
}

func (m *Alpn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alpn.Unmarshal(m, b)
}
func (m *Alpn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alpn.Marshal(b, m, deterministic)
}
func (m *Alpn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alpn.Merge(m, src)
}
func (m *Alpn) XXX_Size() int {
	return xxx_messageInfo_Alpn.Size(m)
}
func (m *Alpn) XXX_DiscardUnknown() {
	xxx_messageInfo_Alpn.DiscardUnknown(m)
}

var xxx_messageInfo_Alpn proto.InternalMessageInfo

func (m *Alpn) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type ForwardEchoResponse struct {
	Output               []string `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardEchoResponse) Reset()         { *m = ForwardEchoResponse{} }
func (m *ForwardEchoResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardEchoResponse) ProtoMessage()    {}
func (*ForwardEchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{5}
}

func (m *ForwardEchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardEchoResponse.Unmarshal(m, b)
}
func (m *ForwardEchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardEchoResponse.Marshal(b, m, deterministic)
}
func (m *ForwardEchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardEchoResponse.Merge(m, src)
}
func (m *ForwardEchoResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardEchoResponse.Size(m)
}
func (m *ForwardEchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardEchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardEchoResponse proto.InternalMessageInfo

func (m *ForwardEchoResponse) GetOutput() []string {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "proto.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "proto.EchoResponse")
	proto.RegisterType((*Header)(nil), "proto.Header")
	proto.RegisterType((*ForwardEchoRequest)(nil), "proto.ForwardEchoRequest")
	proto.RegisterType((*Alpn)(nil), "proto.Alpn")
	proto.RegisterType((*ForwardEchoResponse)(nil), "proto.ForwardEchoResponse")
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_08134aea513e0001) }

var fileDescriptor_08134aea513e0001 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xe3, 0x4b, 0x60, 0x4c, 0x00, 0x6d, 0x22, 0xb4, 0x44, 0x08, 0x2c, 0x4b, 0x28, 0x7e,
	0x21, 0x20, 0xf3, 0x05, 0x48, 0x80, 0x78, 0xa1, 0x0f, 0xdb, 0xbe, 0x57, 0xae, 0x33, 0xaa, 0xa3,
	0xda, 0x5e, 0x67, 0x2f, 0xa9, 0xfa, 0x07, 0xfd, 0xa1, 0xfe, 0x5f, 0xb5, 0x97, 0x28, 0x8e, 0x5a,
	0xf5, 0x69, 0x67, 0xce, 0x9c, 0x3d, 0x7b, 0xf6, 0x0c, 0x00, 0xd6, 0x0d, 0x5f, 0x0f, 0x82, 0x2b,
	0x4e, 0x62, 0x7b, 0xe4, 0x2b, 0x48, 0xff, 0xd4, 0x0d, 0x67, 0xb8, 0xd3, 0x28, 0x15, 0xa1, 0x30,
	0xed, 0x50, 0xca, 0xea, 0x1a, 0x69, 0x90, 0x05, 0xc5, 0x6b, 0x76, 0x68, 0xf3, 0x02, 0xde, 0x38,
	0xa2, 0x1c, 0x78, 0x2f, 0xf1, 0x05, 0xe6, 0x0f, 0x48, 0xfe, 0x61, 0xb5, 0x41, 0x41, 0xde, 0x43,
	0x78, 0x83, 0x77, 0x7e, 0x6e, 0x4a, 0xb2, 0x80, 0x78, 0x5f, 0xb5, 0x1a, 0xe9, 0xc4, 0x62, 0xae,
	0xc9, 0x1f, 0x26, 0x40, 0xfe, 0x72, 0x71, 0x5b, 0x89, 0xcd, 0xd8, 0xcc, 0x02, 0xe2, 0x9a, 0xeb,
	0x5e, 0x59, 0x81, 0x98, 0xb9, 0xc6, 0x88, 0xee, 0x06, 0x69, 0x05, 0x62, 0x66, 0x4a, 0xf2, 0x15,
	0xde, 0xaa, 0x6d, 0x87, 0x5c, 0xab, 0xcb, 0x6e, 0x5b, 0x0b, 0x2e, 0x69, 0x98, 0x05, 0x45, 0xc8,
	0x66, 0x1e, 0xfd, 0x6f, 0x41, 0x73, 0x51, 0x8b, 0x96, 0x46, 0xce, 0x8d, 0x16, 0x2d, 0x59, 0xc1,
	0xb4, 0xb1, 0x4e, 0x25, 0x8d, 0xb3, 0xb0, 0x48, 0xcb, 0x99, 0x0b, 0x67, 0xed, 0xfc, 0xb3, 0xc3,
	0x74, 0xfc, 0xd9, 0xe4, 0xe4, 0xb3, 0xc6, 0x63, 0xa3, 0xd4, 0x50, 0xd2, 0x69, 0x16, 0x14, 0xaf,
	0x98, 0x6b, 0x08, 0x81, 0xa8, 0x46, 0xa1, 0x28, 0x58, 0xb2, 0xad, 0x0f, 0x61, 0xa4, 0xc7, 0x30,
	0xbe, 0x40, 0x54, 0xb5, 0x43, 0x4f, 0x67, 0x59, 0x50, 0xa4, 0x65, 0xea, 0xdf, 0xfe, 0xd5, 0x0e,
	0x3d, 0xb3, 0x03, 0xf2, 0x19, 0x40, 0xa2, 0xd8, 0xa3, 0x38, 0xab, 0x3a, 0xa4, 0x0b, 0x7b, 0x73,
	0x84, 0xe4, 0x9f, 0x20, 0x32, 0xec, 0x63, 0xaa, 0x41, 0x16, 0x1e, 0x53, 0xfd, 0x06, 0xf3, 0x93,
	0x50, 0xfd, 0xe2, 0x3e, 0x40, 0xc2, 0xb5, 0x1a, 0xb4, 0xf2, 0x6c, 0xdf, 0x95, 0xf7, 0x01, 0xbc,
	0x33, 0xc4, 0x0b, 0x94, 0xea, 0x1c, 0xc5, 0x7e, 0x5b, 0x23, 0xf9, 0x0e, 0x91, 0x81, 0x08, 0xf1,
	0xde, 0x46, 0xdb, 0x59, 0xce, 0x4f, 0x30, 0x2f, 0xfe, 0x1b, 0xd2, 0xd1, 0x9b, 0xe4, 0xa3, 0xe7,
	0x3c, 0x5d, 0xee, 0x72, 0xf9, 0xdc, 0xc8, 0xa9, 0x5c, 0x25, 0x76, 0xf4, 0xf3, 0x31, 0x00, 0x00,
	0xff, 0xff, 0x43, 0xa9, 0xdc, 0x42, 0xb0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoTestServiceClient is the client API for EchoTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoTestServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	ForwardEcho(ctx context.Context, in *ForwardEchoRequest, opts ...grpc.CallOption) (*ForwardEchoResponse, error)
}

type echoTestServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoTestServiceClient(cc *grpc.ClientConn) EchoTestServiceClient {
	return &echoTestServiceClient{cc}
}

func (c *echoTestServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/proto.EchoTestService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoTestServiceClient) ForwardEcho(ctx context.Context, in *ForwardEchoRequest, opts ...grpc.CallOption) (*ForwardEchoResponse, error) {
	out := new(ForwardEchoResponse)
	err := c.cc.Invoke(ctx, "/proto.EchoTestService/ForwardEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoTestServiceServer is the server API for EchoTestService service.
type EchoTestServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	ForwardEcho(context.Context, *ForwardEchoRequest) (*ForwardEchoResponse, error)
}

func RegisterEchoTestServiceServer(s *grpc.Server, srv EchoTestServiceServer) {
	s.RegisterService(&_EchoTestService_serviceDesc, srv)
}

func _EchoTestService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoTestServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EchoTestService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoTestServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoTestService_ForwardEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardEchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoTestServiceServer).ForwardEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EchoTestService/ForwardEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoTestServiceServer).ForwardEcho(ctx, req.(*ForwardEchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoTestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EchoTestService",
	HandlerType: (*EchoTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoTestService_Echo_Handler,
		},
		{
			MethodName: "ForwardEcho",
			Handler:    _EchoTestService_ForwardEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}
