# WITH_MODSECURITY is used to switch between the pure proxyv2 image and the proxyv2 image with ModSecurity dependencies
# Values: with_modsecurity, without_modsecurity
ARG WITH_MODSECURITY=without_modsecurity

# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
FROM gcr.io/istio-release/base:${BASE_VERSION} as default

# The following section is used as base image if BASE_DISTRIBUTION=distroless
# This image is a custom built debian11 distroless image with multiarchitecture support.
# It is built on the base distroless image, with iptables binary and libraries added
# The source can be found at https://github.com/istio/distroless/tree/iptables
# This version is from commit a2477f8b37647391020a12527a3a7126ced2b582.
FROM gcr.io/istio-release/iptables@sha256:e5bbbcdab26db1b5bf580bd823204dc82485545e27ce877ca2ad2eb0dc3b55a0 as distroless

# Prepare the system libraries, adding ModSecurity dependency libraries to there.
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION} as final_image_libs
FROM docker.io/istio/base:${BASE_VERSION} as modsecurity_deps

COPY --from=final_image_libs /lib/x86_64-linux-gnu /etc/libs/lib/x86_64-linux-gnu
COPY --from=final_image_libs /usr/lib/x86_64-linux-gnu /etc/libs/usr/lib/x86_64-linux-gnu
COPY modsecurity_plugin_deps /etc/modsecurity_plugin_deps

# finally, make the final system libraries, adding ModSecurity dependency libraries
# which don't exist in the existing system libraries. Note that this cp cannot be 
# moved to the next FROM section because the final image doesn't have cp
WORKDIR /etc/modsecurity_plugin_deps/
# Use cp, not COPY, because COPY overwrites existing files while cp -n keeps existing ones.
RUN cp -r --parents -n ./* /etc/libs/


# This will build the final image based on either default or distroless from above
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION} as build_without_modsecurity

WORKDIR /

ARG proxy_version
ARG istio_version
ARG SIDECAR=envoy

# Copy Envoy bootstrap templates used by pilot-agent
COPY envoy_bootstrap.json /var/lib/istio/envoy/envoy_bootstrap_tmpl.json
COPY gcp_envoy_bootstrap.json /var/lib/istio/envoy/gcp_envoy_bootstrap_tmpl.json

# Install Envoy.
COPY $SIDECAR /usr/local/bin/$SIDECAR

# Environment variable indicating the exact proxy sha - for debugging or version-specific configs 
ENV ISTIO_META_ISTIO_PROXY_SHA $proxy_version
# Environment variable indicating the exact build, for debugging
ENV ISTIO_META_ISTIO_VERSION $istio_version

COPY pilot-agent /usr/local/bin/pilot-agent

COPY stats-filter.wasm /etc/istio/extensions/stats-filter.wasm
COPY stats-filter.compiled.wasm /etc/istio/extensions/stats-filter.compiled.wasm
COPY metadata-exchange-filter.wasm /etc/istio/extensions/metadata-exchange-filter.wasm
COPY metadata-exchange-filter.compiled.wasm /etc/istio/extensions/metadata-exchange-filter.compiled.wasm

# This will build the final image with the dependencies of ModSecurity filter plugin installed
# hadolint ignore=DL3006
FROM build_without_modsecurity as build_with_modsecurity

# Embed OWASP Core Rule Set
COPY owasp-modsecurity-crs /etc/owasp-modsecurity-crs

# Copy ModSecurity dependency libraries. COPY overwrites the entire directory, but it's OK because this direcroy
# includes the original system libraries as well. This is kind of a hack to handle with ModSecurity dependencies.
# We will work on linking ModSecurity statically to remove these parts soon.
COPY --from=modsecurity_deps /etc/libs/lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
COPY --from=modsecurity_deps /etc/libs/usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu

# Switch the final image depending on whether ModSecurity is built with or without.
# hadolint ignore=DL3006
FROM build_${WITH_MODSECURITY}

# The pilot-agent will bootstrap Envoy.
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
