apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ workspaceName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ workspaceName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ productNs }}
  configMode: {{ mode }}
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ trafficGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ trafficGroupName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ reviewsNs }}
  configMode: {{ mode }}
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ securityGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ securityGroupName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ productNs }}
    - {{ clusterName }}/{{ reviewsNs }}
    - {{ clusterName }}/{{ ratingsNs }}
      
  configMode: {{ mode }}
