apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ gatewayGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ gatewayGroupName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ (namespaces and namespaces['product']) or namespace }}
  configMode: {{ mode }}
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ trafficGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ trafficGroupName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ (namespaces and namespaces['reviews']) or namespace }}
  configMode: {{ mode }}
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ securityGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ securityGroupName }}
  namespaceSelector:
    names:
    {% if namespaces -%}
    {% for ns in namespaces %}- {{ clusterName }}/{{ namespaces[ns] }}
    {% endfor -%}
    {% else -%}
    - {{ clusterName }}/{{ namespace }}
    {% endif %}
  configMode: {{ mode }}
