# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
name: "build"

on:
  push:
    branches:
    - tcc
  pull_request:
    branches:
    - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all tags and branches

    - run: make -e T=-v build binaries-test

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make -e T=-v init racetest

  release-test:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all tags and branches

    - run: |
        docker run \
        --rm=true \
        -t \
        -e BUILD_WITH_CONTAINER=0 \
        --mount "type=bind,source=${PWD},destination=/work,consistency=cached" \
        --mount "type=volume,source=go,destination=/go,consistency=cached" \
        --mount "type=volume,source=gocache,destination=/gocache,consistency=cached" \
        -w /work \
        --entrypoint=entrypoint \
        --privileged \
        gcr.io/istio-testing/build-tools:release-1.7-2020-10-12T16-50-25 \
        prow/release-test.sh

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make lint

  gencheck:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make gen-check
