# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
name: "build"

on:
  push:
    branches:
    - tcc
  pull_request:
    branches:
    - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all tags and branches

    - run: make -e T=-v build binaries-test

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make -e T=-v init racetest

  release-test:
    runs-on: [self-hosted, linux, x64, medium] # we use a self-host runner here to get more disk space

    container:
      image: docker.io/yskopets/build-tools:release-1.7-2020-10-12T16-50-25 # IMG
      env:
        BUILD_WITH_CONTAINER: "0"

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all tags and branches

    - name: "Configure gcloud"
      env:
        # secrets should be populated according to https://github.com/tetrateio/infosec/issues/59
        PROJECT_ID: ${{ secrets.GCP_INTERNAL_CONTAINERS_PROJECT_ID }}
        SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_INTERNAL_CONTAINERS_SERVICE_ACCOUNT_KEY }}
      run: |
        KEY_FILE=${HOME}/gcp.key.json
        echo "${SERVICE_ACCOUNT_KEY}" | base64 -d > ${KEY_FILE}
        gcloud auth activate-service-account --key-file=${KEY_FILE} --project=${PROJECT_ID}
        rm ${KEY_FILE}

    - name: "Configure Docker to use gcloud as credentials helper"
      run: gcloud auth configure-docker

    - env:
        DOCKER_HUB: gcr.io/tetrate-internal-containers
        PUBLISH_GCS: "0" # don't publish release artifacts to GCS
      run: prow/release-commit.sh

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make lint

  gencheck:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make gen-check
