apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: tsb-gateway-{{ ns }}
  namespace: {{ ns }}
spec:
  kubeSpec:
    service:
      type: NodePort
    annotations:
        traffic.istio.io/nodeSelector: ‘{“kubernetes.io/os”:“linux”}’
