apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trafficgenerator
  name: trafficgenerator
  namespace: {{ ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: trafficgenerator
    spec:
      containers:
      - command: [ "/bin/bash", "-c", "--" ]
        args:
        - |
          PORT=$(kubectl get service -n {{ ns }} {{ serviceName }} -o jsonpath='{.spec.ports[?(@.port==443)].nodePort}')
          IP=$(kubectl get nodes --output "jsonpath={.items[0].status.addresses[?(@.type=='ExternalIP')].address}")
          while :; do
            curl "https://{{ hostname }}/productpage" --resolve "{{ hostname }}:443:$IP:$PORT" --cacert /etc/bookinfo/bookinfo-ca.crt #>/dev/null 2>&1
            sleep 10
          done
        image: bitnami/kubectl
        imagePullPolicy: IfNotPresent
        name: trafficgenerator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/bookinfo
          name: bookinfo
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bookinfo
        secret:
          defaultMode: 420
          secretName: {{ secretName }}
      serviceAccountName: {{ saName }}
